// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCSXuMuQnuRP-0C5yUKDhA-GC8CRLAwuY',
    appId: '1:312078389304:web:7f74aa873a767072c656cd',
    messagingSenderId: '312078389304',
    projectId: 'chat-bot-407bc',
    authDomain: 'chat-bot-407bc.firebaseapp.com',
    storageBucket: 'chat-bot-407bc.firebasestorage.app',
    measurementId: 'G-QJGTPSLMQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1C6Hzw9KG9NFMaGsOh5JhPpr6TGx89Ok',
    appId: '1:312078389304:android:81875b7a802e942cc656cd',
    messagingSenderId: '312078389304',
    projectId: 'chat-bot-407bc',
    storageBucket: 'chat-bot-407bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkkz0zsykMKC_6D8uYBaCk3Z6mMiEuTWM',
    appId: '1:312078389304:ios:50c85aebd468a242c656cd',
    messagingSenderId: '312078389304',
    projectId: 'chat-bot-407bc',
    storageBucket: 'chat-bot-407bc.firebasestorage.app',
    iosBundleId: 'com.example.chatbotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkkz0zsykMKC_6D8uYBaCk3Z6mMiEuTWM',
    appId: '1:312078389304:ios:50c85aebd468a242c656cd',
    messagingSenderId: '312078389304',
    projectId: 'chat-bot-407bc',
    storageBucket: 'chat-bot-407bc.firebasestorage.app',
    iosBundleId: 'com.example.chatbotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCSXuMuQnuRP-0C5yUKDhA-GC8CRLAwuY',
    appId: '1:312078389304:web:1917595907d2c79bc656cd',
    messagingSenderId: '312078389304',
    projectId: 'chat-bot-407bc',
    authDomain: 'chat-bot-407bc.firebaseapp.com',
    storageBucket: 'chat-bot-407bc.firebasestorage.app',
    measurementId: 'G-1P7DB8PKQ8',
  );
}
